### ISSUE TITLE
Move printers to Wireless VLAN

### ISSUE THREAD

**Issue by eby** [aadl/printing#4]
Since we are moving towards honor system without a fancy queue setup we should move the printers to the wireless vlan so that the built in Airprint just works.

With the eventual segmenting of that vlan we'll need to have the cups server on both public and wireless so it can talk to everything.

**Comment by eby** [comment]
Proposed IPs. Includes swapping the xerox copier at Traverwood with a xm1145.

| Location      | Printer       | IP              | Model     |
| ------------- | ------------- | --------------- | --------- |
| Downtown      | 1st Bathrooms | 10.10.0.21      | XM1145    |
| Downtown      | 2nd Reference | 10.10.0.22      | X463de    |
| Downtown      | 3rd Fiche     | 10.10.0.23      | X463de    |
| Malletts      | Near Lab      | 10.10.0.24      | XM1145    |
| Malletts      | Near Bathrooms| 10.10.0.25      | XM1145    |
| Pittsfield    | Near Desk     | 10.10.0.26      | X463de    |
| Pittsfield    | Near Lab      | 10.10.0.27      | XM1145    |
| Traverwood    | Near Lab      | 10.10.0.28      | X463de    |
| Traverwood    | Near Bathrooms| 10.10.0.29      | XM1145    |
| Westgate      | 1 (by lab)   | 10.10.0.30      | XM1145    |
| Westgate      | 2 (by lab)   | 10.10.0.31      | XM1145    |

**Comment by eby** [comment]
Westgate done for public.

Traverwood, MCB and Pittsfield will need the rest of the cisco access points swapped for ubnt

**Comment by eby** [comment]
MCB and Traverwood are ready to switch. Will try to do this weekend. Only mini is locker computer so isn't big deal if update public ip later.

- MCB Lab / 00:21:b7:99:e5:eb / sw3 - 25
- MCB Copier / 00:21:b7:b1:29:ee / sw2 - 44
- Traverwood Lab / 00:21:B7:8A:F5:6C / sw1 - C1
- Pittsfield Printer / 00:21:b7:18:95:7a / sw2 - 2
- Pittsfield Copier / 00:21:b7:b1:29:81 / sw1 - A8

**Todo**
- [x] Update DHCP
- [x] Reboot printers and update vlan
- [x] Update printer queues on lutefisk
- [x] Update printer queues on conky
- [x] Update printer queues on cups
- [x] Make sure printer airprint settings / name makes sense

**Comment by taleon** [comment]
Pittsfield APs will be swapped out Sunday, so could just do all at once if that's easier.

**Comment by eby** [comment]
I can move the pitts printers ahead of time. They just won't show up as airprint until the new access points roll out.

**Comment by eby** [comment]
This is all set now. Need to go through printers and make sure airprint names are all set and then update README
